---
- name: add mongodb 4.x signing key
  ansible.builtin.apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"

- name: add mongodb 4.x repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ lin_apt_arch }}] https://repo.mongodb.org/apt/ubuntu {{ repodir }} multiverse"
    filename: mongodb
    mode: 0644
  vars:
    repodir: "{{ codename }}/mongodb-org/{{ mongodb_version }}"
    ## workaround for mongodb 4.x repo not yet ready on focal
    codename: "{{ 'bionic' if _codename == 'focal' and mongodb_focal_fix |bool else _codename }}"
    _codename: "{{ ansible_lsb.codename }}"

- name: install mongodb packages
  ansible.builtin.apt:
    name: "{{ pkg_list |select |join(',') }}"
  vars:
    pkg_list: "{{ pkg_mongodb + pkg_pymongo_noxenial + pkg_pip + pkg_helpers }}"
    pkg_mongodb: ['mongodb-org']
    use_py2: "{{ lin_use_python2 |bool }}"
    pkg_pip: "{{ ['python3-pip', ('python-pip' if use_py2 else '')] }}"
    ## don't install ancient pymongo deb on xenial
    ## (it will stand in pip3 package imports and fail)
    pkg_pymongo_noxenial: "{{ [] if ansible_lsb.codename == 'xenial' else pkg_pymongo }}"
    pkg_pymongo: "{{ ['python3-pymongo', ('python-pymongo' if use_py2 else '')] }}"
    ## ssl-cert for snakeoil certificate
    ## jq for parsing json
    pkg_helpers: [ssl-cert, jq]

- name: upgrade to pymongo >3.7 to avoid problems with SCRAM-SHA-256
  ## see: https://github.com/ansible/ansible/issues/44970
  ansible.builtin.pip:
    name: pymongo>3.7
    executable: "{{ item }}"
  loop: "{{ lin_use_python2 |bool |ternary(['pip','pip3'], ['pip3']) }}"
...
