---
- name: install and configure netdata
  ansible.builtin.import_tasks: setup.yml
  tags: srv_netdata_setup

- name: monitor some directory sizes
  ansible.builtin.template:
    src: dirmon/dirmon.chart.sh
    dest: /usr/libexec/netdata/charts.d/dirmon.chart.sh
    mode: 0644
  when: disk_dirs |d('')
  notify: restart netdata service
  vars:
    update_every: "{{ srv_netdata_update_dirs_every }}"
    chart_priority: 90000
    disk_dirs: "{{ _disk_dirs_list |join(',') }}"
    _disk_dirs_tuples: "{{ srv_netdata_disk_dirs |d({},true) |dictsort }}"
    _disk_dirs_list: >
      {% set ns = namespace(items = []) -%}
      {% for name, path in _disk_dirs_tuples -%}
        {% set ns.items = ns.items + ['%s(%s)' % (path, name)] -%}
      {% endfor -%}
      {{ ns.items }}
  tags: srv_netdata_dirs

- name: customize netdata alarms
  ansible.builtin.import_tasks: alarms.yml
  when: srv_netdata_alarms |d({})
  tags: srv_netdata_alarms

- name: setup netdata site in nginx
  ansible.builtin.template:
    src: netdata/nginx.conf
    dest: "{{ nginx_site_dir }}/netdata.conf"
    mode: 0644
  notify: reload nginx service
  vars:
    ssl_port: "{{ nginx_ssl_port_internal |d(0) |int }}"
    ssl_host_port: "{{ ':%s' % ssl_port if ssl_port |int else '' }}"
  when: srv_netdata_nginx_site |d('')
  tags: srv_netdata_nginx

- name: register with netdata api server
  ansible.builtin.command:
    cmd: netdata-claim.sh -token={{ token }} -rooms={{ rooms }} -url={{ url }}
    creates: /var/lib/netdata/cloud.d/claimed_id
  notify: restart netdata service
  vars:
    token: "{{ srv_netdata_token |d('') }}"
    rooms: "{{ srv_netdata_rooms |d('') }}"
    url: https://app.netdata.cloud
  when:
    - token |d('')
    - rooms |d('')
  tags: srv_netdata_claim
...
