---
dependencies:
  - ivansible.lin_base  # for lin_use_firewall

galaxy_info:
  role_name: lin_dante_auth
  author: "Ivan Andreev"
  description: "install dante proxy server with authentication"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - proxy

  github_branch: master
...
