---
# defaults file for ivansible.lin_mtproxy

mtproxy_secret: deadbeefdeadbeef0123456789abcdef
mtproxy_port: 13128
mtproxy_bindip: 0.0.0.0
mtproxy_direct: yes
mtproxy_secure: yes

mtproxy_release: latest
mtproxy_reinstall: no
mtproxy_bin_file: /usr/local/sbin/mtg
mtproxy_rmdocker: no
...
