---
# defaults file for ivansible.lin_dante_auth

dante_port: 1080
dante_direct: yes
# dante username must start with 'dante_' because it's a global linux user
dante_user: dante_socks
dante_pass: secret

# see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#hash-filters
dante_salt: "{{ 32100 |random(seed=inventory_hostname) |string }}"

dante_deb_url: https://lug.mtu.edu/ubuntu/pool/universe/d/dante/dante-server_1.4.2+dfsg-2build1_amd64.deb
...
