---
- name: gather installed nxserver version
  ## should ignore linter warning about pipefail here
  ## it's perfectly valid to fail if package is not installed
  # noqa 306
  ansible.builtin.shell:
    cmd: dpkg --list nomachine | awk '/^ii / {print $3}'
  changed_when: false
  register: _nx_dpkg_result

- name: install nxserver package
  ansible.builtin.apt:
    deb: "{{ deb_url }}"
  vars:
    ## install on amd64 or arm64
    deb_url: "{{ lin_nxserver_deb_url |replace('ARCH', lin_apt_arch) }}"
    ## extract new version from url
    new_ver: "{{ deb_url |regex_replace('^.*?_([\\d\\._]{3,})_.*$', '\\1') | replace('_', '-') }}"
    ## stdout is undefined in check mode
    old_ver: "{{ _nx_dpkg_result.stdout |d('') }}"
  when: new_ver != old_ver
  ## fix intermittent network errors on .ru boxes
  register: _nx_apt_result
  until: _nx_apt_result.msg |d('') is not search('timed out')
...
