---
dependencies:
  - ivansible.base.linux  # for common defaults, handlers, modules

galaxy_info:
  role_name: lin_nxserver
  author: "Ivan Andreev"
  description: "nomachine nxserver and window manager on linux"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - ansible
    - nomachine
    - nxserver

  github_branch: master
...
